name: Deploy Laravel to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2

      - name: Install dependencies
        run: composer install --no-dev --optimize-autoloader

      - name: Create SQLite file
        run: |
          mkdir -p database
          touch database/database.sqlite

      - name: Set CI environment
        run: |
          echo "DB_CONNECTION=sqlite" >> .env
          echo "DB_DATABASE=/tmp/database.sqlite" >> .env

      - name: Optimize Laravel
        run: |
          php artisan config:clear || true
          php artisan cache:clear || true
          php artisan route:clear || true

      # ✅ IMPORTANT FIX ADDED
      - name: Move Laravel public to root
        run: |
          cp -r public/* .
          rm -rf public

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_53CBEC304047407D8E5B6D2DCAC12C21 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F06F6BBF379C436B9C666C0EE687D5CF }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_7513B5D821